### ISSUE TITLE
Doesn't start, seeing the following error on sandstorm:

### ISSUE THREAD

**Issue by pgrm** [simonv3/IdeaOtter#5]
```
** Starting Meteor...

/programs/server/node_modules/fibers/future.js:278
                        throw(ex);
                              ^
Error: failed to connect to [127.0.0.1:8001]
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:98:1)
    at packages/accounts-base/accounts_common.js:141:1
    at /programs/server/packages/accounts-base.js:243:4
    at /programs/server/packages/accounts-base.js:1659:3
    at /programs/server/boot.js:222:10
    - - - - -
    at [object Object].<anonymous> (/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:448:13)
```

**Comment by pgrm** [comment]
Update - ok, after like 5min it finally got running. Any ideas why it couldn't connect in the first place? Or does it just take so long to start meteor applications in sandstorm?

**Comment by simonv3** [comment]
@pgrm It can take a while to download everything, but it shouldn't throw any errors. 

It looks like the error is originating in a file that isn't being used anymore though. It's a good reminder to remove it in the next upgrade - thanks for the error stack - I'll investigate that line specifically too.

**Comment by pgrm** [comment]
@simonv3 thx for the response. Maybe something changed in the meanwhile, but I wouldn't see what it could be downloading so much. The server has 100MBit up/down in some data center and is most of the time not running too much with its 16GB memory and Core i5 quad core processor. Other applications like rocket chat or wekan do start relatively quick. For sure within 10-15s, that's why I was thinking after half a minute that the app isn't working and dead. Only once I saw here that it actually worked for others I went back and realised - yeah, it's online :)

**Comment by simonv3** [comment]
@pgrm Hmm, so you're saying that the long load time is when the grain starts? Is it every time that it starts? Or is it just on the initial set up?

**Comment by pgrm** [comment]
Ok, so just checking another time, also creating a new grain, and the error doesn't show up anymore and the load time is normal within ~10s (didn't really measure it) - did you update it, or maybe there was a problem when the grain was created?

Otherwise from my side, you can close this now, thx

**Comment by simonv3** [comment]
I didn't update it, odd. I'll close it, but definitely let me know if weird things continue happening. Might be something to raise with the larger sandstorm team?

**Comment by pgrm** [comment]
Yeah, in case I'll manage to ever reproduce it :)
